version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - ./certs:/etc/nginx/certs
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
    depends_on:
      - "ui"
      - "api"
      - "auth"
  ui:
    image: recipe_ui
    ports:
      - "3003:3003"
    environment:
      - VIRTUAL_HOST=recepies.local
      - VIRTUAL_PORT=3003
    volumes:
      - ./files:/files/images:ro
    depends_on:
      - "api"
      - "auth"
  api:
    image: recepies
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=mongo
      - DATABASE=recepies
      - FILEBASE=/files
      - SECRET=eEMAr0UrJmyrLvwA2jcd8tPC93NTmE5cWpx9abAkc5quNysKZLwlxPHvOgNO
      - PROTECTED_ENDPOINTS="recipe:create,recipe:update,recipe:delete,recipe:upload"
    volumes:
      - ./files:/files
    depends_on:
      - "mongo"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5000"
  auth:
    image: auth
    ports:
      - "3002:3002"
    environment:
      - MONGODB_HOST=mongo
      - DATABASE=recepies
      - SECRET=eEMAr0UrJmyrLvwA2jcd8tPC93NTmE5cWpx9abAkc5quNysKZLwlxPHvOgNO
    depends_on:
      - "mongo"
  mongo:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    command: mongod --bind_ip_all
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline/:ro
      #- ./logstash/settings:/usr/share/logstash/config:ro
